site_name: sfapi_client
watch: [src/sfapi_client]
nav:
  - Overview: index.md
  - Usage:
      - QuickStart: quickstart/
      - Examples: examples/
  - API Reference: reference/
  - Community:
      - Contributing: community/contributing.md

theme:
  name: "material"
  features:
    - content.code.copy
    - navigation.sections
extra_javascript:
  - javascript/apiselector.js

plugins:
- search
- autorefs
- mkdocs-jupyter:
    include: ["*.ipynb"]
    ignore: ["docs/*.py"]
- gen-files:
    scripts:
    - docs/gen_sync.py
    - docs/gen_examples.py
- literate-nav:
    nav_file: SUMMARY.txt
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_style: sphinx
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: no

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
