site_name: sfapi_client
watch: [src/sfapi_client]
nav:
- Home:
  - Overview: index.md
- API Reference: reference/

theme:
  name: "material"

extra_javascript:
  - javascript/apiselector.js

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_sync.py
- literate-nav:
    nav_file: SUMMARY.txt
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_style: sphinx
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: no

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences