# generated by datamodel-codegen:
#   filename:  job_status_response_squeue.json
#   timestamp: 2023-02-28T15:47:20+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class OutputItem(BaseModel):
    account: Optional[str] = None
    tres_per_node: Optional[str] = None
    min_cpus: Optional[str] = None
    min_tmp_disk: Optional[str] = None
    end_time: Optional[str] = None
    features: Optional[str] = None
    group: Optional[str] = None
    over_subscribe: Optional[str] = None
    jobid: Optional[str] = None
    name: Optional[str] = None
    comment: Optional[str] = None
    time_limit: Optional[str] = None
    min_memory: Optional[str] = None
    req_nodes: Optional[str] = None
    command: Optional[str] = None
    priority: Optional[str] = None
    qos: Optional[str] = None
    reason: Optional[str] = None
    field_: Optional[str] = None
    st: Optional[str] = None
    user: Optional[str] = None
    reservation: Optional[str] = None
    wckey: Optional[str] = None
    exc_nodes: Optional[str] = None
    nice: Optional[str] = None
    s_c_t: Optional[str] = Field(None, alias="s:c:t")
    exec_host: Optional[str] = None
    cpus: Optional[str] = None
    nodes: Optional[str] = None
    dependency: Optional[str] = None
    array_job_id: Optional[str] = None
    sockets_per_node: Optional[str] = None
    cores_per_socket: Optional[str] = None
    threads_per_core: Optional[str] = None
    array_task_id: Optional[str] = None
    time_left: Optional[str] = None
    time: Optional[str] = None
    nodelist: Optional[str] = None
    contiguous: Optional[str] = None
    partition: Optional[str] = None
    nodelist_reason_: Optional[str] = Field(None, alias="nodelist(reason)")
    start_time: Optional[str] = None
    state: Optional[str] = None
    uid: Optional[str] = None
    submit_time: Optional[str] = None
    licenses: Optional[str] = None
    core_spec: Optional[str] = None
    schednodes: Optional[str] = None
    work_dir: Optional[str] = None


class JobStatusResponseSqueue(BaseModel):
    status: Optional[str] = None
    output: Optional[List[OutputItem]] = None
    error: Optional[Any] = None
