# generated by datamodel-codegen:
#   filename:  job_status_response_sacct.json
#   timestamp: 2023-02-28T15:47:20+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class OutputItem(BaseModel):
    account: Optional[str] = None
    admincomment: Optional[str] = None
    alloccpus: Optional[str] = None
    allocnodes: Optional[str] = None
    alloctres: Optional[str] = None
    associd: Optional[str] = None
    avecpu: Optional[str] = None
    avecpufreq: Optional[str] = None
    avediskread: Optional[str] = None
    avediskwrite: Optional[str] = None
    avepages: Optional[str] = None
    averss: Optional[str] = None
    avevmsize: Optional[str] = None
    blockid: Optional[str] = None
    cluster: Optional[str] = None
    comment: Optional[str] = None
    constraints: Optional[str] = None
    consumedenergy: Optional[str] = None
    consumedenergyraw: Optional[str] = None
    cputime: Optional[str] = None
    cputimeraw: Optional[str] = None
    dbindex: Optional[str] = None
    derivedexitcode: Optional[str] = None
    elapsed: Optional[str] = None
    elapsedraw: Optional[str] = None
    eligible: Optional[str] = None
    end: Optional[str] = None
    exitcode: Optional[str] = None
    flags: Optional[str] = None
    gid: Optional[str] = None
    group: Optional[str] = None
    jobid: Optional[str] = None
    jobidraw: Optional[str] = None
    jobname: Optional[str] = None
    layout: Optional[str] = None
    maxdiskread: Optional[str] = None
    maxdiskreadnode: Optional[str] = None
    maxdiskreadtask: Optional[str] = None
    maxdiskwrite: Optional[str] = None
    maxdiskwritenode: Optional[str] = None
    maxdiskwritetask: Optional[str] = None
    maxpages: Optional[str] = None
    maxpagesnode: Optional[str] = None
    maxpagestask: Optional[str] = None
    maxrss: Optional[str] = None
    maxrssnode: Optional[str] = None
    maxrsstask: Optional[str] = None
    maxvmsize: Optional[str] = None
    maxvmsizenode: Optional[str] = None
    maxvmsizetask: Optional[str] = None
    mcslabel: Optional[str] = None
    mincpu: Optional[str] = None
    mincpunode: Optional[str] = None
    mincputask: Optional[str] = None
    ncpus: Optional[str] = None
    nnodes: Optional[str] = None
    nodelist: Optional[str] = None
    ntasks: Optional[str] = None
    priority: Optional[str] = None
    partition: Optional[str] = None
    qos: Optional[str] = None
    qosraw: Optional[str] = None
    reason: Optional[str] = None
    reqcpufreq: Optional[str] = None
    reqcpufreqmin: Optional[str] = None
    reqcpufreqmax: Optional[str] = None
    reqcpufreqgov: Optional[str] = None
    reqcpus: Optional[str] = None
    reqmem: Optional[str] = None
    reqnodes: Optional[str] = None
    reqtres: Optional[str] = None
    reservation: Optional[str] = None
    reservationid: Optional[str] = None
    reserved: Optional[str] = None
    resvcpu: Optional[str] = None
    resvcpuraw: Optional[str] = None
    start: Optional[str] = None
    state: Optional[str] = None
    submit: Optional[str] = None
    suspended: Optional[str] = None
    systemcpu: Optional[str] = None
    systemcomment: Optional[str] = None
    timelimit: Optional[str] = None
    timelimitraw: Optional[str] = None
    totalcpu: Optional[str] = None
    tresusageinave: Optional[str] = None
    tresusageinmax: Optional[str] = None
    tresusageinmaxnode: Optional[str] = None
    tresusageinmaxtask: Optional[str] = None
    tresusageinmin: Optional[str] = None
    tresusageinminnode: Optional[str] = None
    tresusageinmintask: Optional[str] = None
    tresusageintot: Optional[str] = None
    tresusageoutave: Optional[str] = None
    tresusageoutmax: Optional[str] = None
    tresusageoutmaxnode: Optional[str] = None
    tresusageoutmaxtask: Optional[str] = None
    tresusageoutmin: Optional[str] = None
    tresusageoutminnode: Optional[str] = None
    tresusageoutmintask: Optional[str] = None
    tresusageouttot: Optional[str] = None
    uid: Optional[str] = None
    user: Optional[str] = None
    usercpu: Optional[str] = None
    wckey: Optional[str] = None
    wckeyid: Optional[str] = None
    workdir: Optional[str] = None


class JobStatusResponseSacct(BaseModel):
    status: Optional[str] = None
    output: Optional[List[OutputItem]] = None
    error: Optional[Any] = None
