from enum import Enum

class Resource(str, Enum):
    perlmutter = "perlmutter"
    cori = "cori"
    dna = "dna"
    dtns = "dtns"
    global_homes = "global_homes"
    global_common = "global_common"
    community_filesystem = "community_filesystem"
    iris = "iris"
    globus = "globus"
    jupyter = "jupyter"
    nersc_center = "nersc_center"
    helpportal = "helpportal"
    website = "website"
    rstudio = "rstudio"
    sgns = "sgns"
    network = "network"
    ldap = "ldap"
    integ_datalanguage = "integ_datalanguage"
    mathematica = "mathematica"
    spin = "spin"
    mongodb = "mongodb"
    matlab = "matlab"
    jgi_int_webservers = "jgi_int_webservers"
    jgidb = "jgidb"
    _int = "int"
    webservers = "webservers"
    ssh_proxy = "ssh-proxy"
    sciencedatabases = "sciencedatabases"
    myproxy = "myproxy"
    nomachine = "nomachine"
    newt = "newt"
    regent = "regent"
    archive = "archive"

Resource.__str__ = lambda self: self.value